sentry:
    dsn: '%env(SENTRY_DSN)%'
    messenger:
        enabled: true
        capture_soft_fails: true
    options:
        environment: '%kernel.environment%'
        release: '%env(VERSION)%'
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'
