FROM nginx:1.20.2-alpine as nginx_build

COPY docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
WORKDIR /var/www/html

RUN mkdir -p public

VOLUME /var/www/html/public

STOPSIGNAL SIGQUIT
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
