FROM php:8.1.7-fpm-alpine3.14 AS php_build

RUN apk add --no-cache \
  acl \
  icu \
  libxslt \
  libzip \
  zlib \
  && apk add --no-cache --virtual .build-deps \
  $PHPIZE_DEPS \
  icu-dev \
  libxslt-dev \
  libzip-dev \
  zlib-dev

RUN docker-php-ext-install intl \
  mysqli \
  opcache \
  pdo \
  pdo_mysql \
  pcntl \
  xsl \
  zip \
  && pecl install apcu \
  && pecl clear-cache \
  && docker-php-ext-enable apcu \
  opcache \
  pdo_mysql

RUN rm -rf /tmp/pear/ \
  && apk del .build-deps

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
RUN sed -i "s/memory_limit = 128M/memory_limit = 512M/g" "$PHP_INI_DIR/php.ini"
COPY docker/php/conf.d/prod.ini $PHP_INI_DIR/conf.d/prod.ini

COPY --from=composer:2.2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

VOLUME /var/www/html/

STOPSIGNAL SIGQUIT
EXPOSE 9000
CMD ["php-fpm"]
